add localization
liujing04/Retrieval-based-Voice-Conversion-WebUI pull request #35
Opened 2023-04-11 14:26 UTC by Katsuyuki-Karasawa

2023-04-11 16:25 UTC, fumiama requested changes

2023-04-11 16:25 UTC, fumiama commented on locale/zh_CN.json
> +    "输入设备/Input Device": "输入设备/Input Device",
既然加了i18n，这种斜杠表示是否不再需要？

2023-04-11 16:36 UTC, Katsuyuki-Karasawa commented on locale/zh_CN.json
> +    "输入设备/Input Device": "输入设备/Input Device",
我认为😌

2023-04-11 23:09 UTC, Katsuyuki-Karasawa commented on locale/zh_CN.json
> +    "输入设备/Input Device": "输入设备/Input Device",
是🤔

2023-04-12 02:48 UTC, merged

2023-04-12 05:56 UTC, CNChTu commented
gui.py中的入口被删除了，现在python gui.py无法正常运行

2023-04-12 05:57 UTC, CNChTu commented
原先在gui.py的330行的程序入口被删除了，直接python gui.py无法正常运行

2023-04-12 05:59 UTC, fumiama commented on extract_locale.py
> +pattern = r'i18n\([^)]*\)'
你光改了这个，代码本身没动啊😂